---
version: "3.0"
services:
  static:
    container_name: homeowner_static
    image: nginx:1.19
    ports:
    - "8080:80"
    volumes:
    - ./nginx:/etc/nginx
    - ./static:/usr/share/nginx/html:ro
    command: [nginx-debug, '-g', 'daemon off;']
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "1UABC/jNtmTsbXqe"
  api:
    build: ./docker/api.Dockerfile
  ui:
    build: ./docker/ui.Dockerfile
