---
version: "3.0"
services:
  static:
    container_name: idp_static
    image: nginx:1.19
    ports:
    - "8080:80"
    volumes:
    - ./nginx:/etc/nginx
    - ./static:/usr/share/nginx/html:ro
    command: [nginx-debug, '-g', 'daemon off;']
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "1UABC/jNtmTsbXqe"
    container_name: idp_db
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: idp_api

  ui:
    build:
      context: .
      dockerfile: ./docker/ui.Dockerfile
    ports:
    - "9090:3000"
    container_name: idp_ui
