---
version: "3.0"
services:
  static:
    network_mode: host
    container_name: idp_static
    image: nginx:1.19.8-alpine
    volumes:
    - ./nginx:/etc/nginx:ro
    - ./static:/usr/share/nginx/html:ro
    - ./logs/nginx:/var/log/nginx:rw
    command: [nginx]

  db:
    network_mode: host
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "1UABC/jNtmTsbXqe"
    container_name: idp_db

  api:
    network_mode: host
    image: idp_api
    container_name: idp_api

  ui:
    network_mode: host
    image: idp_ui
    ports:
    - "9090:3000"
    container_name: idp_ui
