---
version: "3.0"
services:
  static:
    container_name: homeowner_static
    image: nginx:1.19
    ports:
    - "8080:80"
    volumes:
    - ./nginx:/etc/nginx
    - ./static:/usr/share/nginx/html:ro
    command: [nginx-debug, '-g', 'daemon off;']
#  database:
#  api:
#  ui:
